In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [9]:
# 1. How many negative numbers are there?
negnums = a[a < 0]
len(negnums)

4

In [10]:
# 2. How many positive numbers are there?
posnums = a[a > 0]
len(posnums)

5

In [17]:
# 3. How many even positive numbers are there?
evenpos = a[a%2 == 0]
evenpos = evenpos[evenpos > 0]
len(evenpos)

3

In [22]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
b = a[a+3 > 0]
len(b)

10

In [24]:
# 5. If you squared each number, what would the new mean and std be?
c = a**2
print(f'The mean would go from {a.mean()} to {c.mean()} and the std would go from {a.std()} to {c.std()}.')

The mean would go from 3.0 to 74.0 and the std would go from 8.06225774829855 to 144.0243035046516.


In [27]:
# 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0.
# This is done by subtracting the mean from each data point. Center the dataset.

d = a - a.mean()
d

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [29]:
# 7. Calculate the z-score for each data point. 
e = (a - a.mean())/a.std()
e

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [30]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [52]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
sum_of_a

55

In [55]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [56]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [61]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

In [62]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = a[0]
for spot in a:
    product_of_a *= spot

product_of_a

3628800

In [66]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for spot in a:
    squares_of_a.append(spot**2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [69]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for spot in a:
    if spot%2 != 0:
        odds_in_a.append(spot)
odds_in_a

[1, 3, 5, 7, 9]

In [70]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for spot in a:
    if spot%2 == 0:
        evens_in_a.append(spot)
evens_in_a

[2, 4, 6, 8, 10]

In [72]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [75]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
b = np.array(b)
sum_of_b = b.sum()
sum_of_b

33

In [77]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b = b.min()
min_of_b

3

In [78]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = b.max()
max_of_b

8

In [79]:
# Exercise 4 - refactor the following using numpy to find the mean of b
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b = b.mean()
mean_of_b

5.5

In [81]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number
product_of_b = b.prod()
product_of_b

20160

In [90]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)
squares_of_b = b**2
squares_of_b.tolist()

[[9, 16, 25], [36, 49, 64]]

In [89]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)
odds_in_b = b[b%2 == 1]
odds_in_b.tolist()

[3, 5, 7]

In [93]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)
evens_in_b = b[b%2 == 0]
evens_in_b.tolist()

[4, 6, 8]

In [95]:
# Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [99]:
# Exercise 10 - transpose the array b.
new_b = b.transpose()
new_b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [105]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
list_b = b.flatten().tolist()
list_b

[3, 4, 5, 6, 7, 8]

In [106]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
lol = b.reshape(6,1)
lol

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [115]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
c = np.array(c)

In [118]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


In [119]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [120]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [121]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [122]:
# Exercise 5 - Transpose c and print out transposed result.
new_c = c.transpose()
new_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [123]:
# Exercise 6 - Get the dot product of the array c with c. 
c_prod = c*c
c_prod

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [124]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
thing = (c*c.transpose()).sum()
thing

261

In [125]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
thing2 = (c*c.transpose()).prod()
thing2

131681894400

In [136]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

In [139]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [140]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [141]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [142]:
# Exercise 4 - Find all the negative numbers in d
neg_d = d[d < 0]
neg_d

array([-90, -30, -45, -45])

In [143]:
# Exercise 5 - Find all the positive numbers in d
pos_d = d[d > 0]
pos_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [150]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [151]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [152]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [154]:
# Exercise 9 - Transpose and then print out the shape of d.
t_d = d.transpose()
t_d

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [155]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])